# Generated by Django 5.2.6 on 2025-09-28 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('reception', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referrer', models.CharField(blank=True, default='', max_length=120)),
                ('note', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reception.patient')),
            ],
        ),
        migrations.CreateModel(
            name='ReferralItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='referrals.referral')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.servicecode')),
            ],
        ),
    ]
