# Generated by Django 5.2.6 on 2025-09-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('service_code', models.CharField(blank=True, max_length=20)),
                ('provider_name', models.CharField(blank=True, max_length=120)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('patient_share', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('base_ins_share', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('clinic_share', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
