# Generated by Django 5.2.6 on 2025-09-28 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('base', 'Base'), ('supp', 'Supplementary')], max_length=4)),
                ('insurer', models.CharField(max_length=120)),
                ('tariff', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('patient_share', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cap_monthly', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.servicecode')),
            ],
        ),
    ]
